### ISSUE TITLE
Open Core version

### ISSUE THREAD

**Issue by alexookah** [HawkysCC/Hackintosh-NUC10i7#12]
Hi i would like to know which version of Open Core contains this repo?
Maybe this should be documented in the Readme.md

**Comment by mrasong** [comment]
hi there, new version on [https://github.com/hackintosh-efi/intel-nuc10](https://github.com/hackintosh-efi/intel-nuc10) with OpenCore 0.6.5, this repo will not update.

**Comment by alexookah** [comment]
@mrasong thank you very much.
maybe update the readme with this repo? :)

**Comment by mrasong** [comment]
already updated, thanks. :)
