### ISSUE TITLE
WiFi支持 是支持板载WiFi嘛？

### ISSUE THREAD

**Issue by xvwvx** [HawkysCC/Hackintosh-NUC10i7#2]
WiFi支持 是支持板载WiFi嘛？WiFi只支持 BigSur嘛？

**Comment by xvwvx** [comment]
找到了 WiFI 支持要配合 https://github.com/OpenIntelWireless/HeliPort 使用

**Comment by liushuai42** [comment]
> 找到了 WiFI 支持要配合 https://github.com/OpenIntelWireless/HeliPort 使用

Up 主的配置的驱动是配合系统 Wifi 管理使用的，不需要这个 HeliPort

**Comment by liushuai42** [comment]
在我的 NUC 上需要更新到最新版本的 AirportItlwm.kext 才能使用，另外暂时还不支持企业认证的 WIFI
