### ISSUE TITLE
搜索不到QQ群

### ISSUE THREAD

**Issue by 8430177** [HawkysCC/Hackintosh-NUC10i7#5]
搜索不到QQ群

**Comment by mrasong** [comment]
> 搜索不到QQ群

591528332

**Comment by 8430177** [comment]
没有，只有一个用户
![image](https://user-images.githubusercontent.com/35485637/102755389-4751a880-43a9-11eb-80c9-cb929c8902e5.png)

**Comment by mrasong** [comment]
已处理
